---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by a.
--- DateTime: 2022/11/5 10:24
---
-- 比较线程标识和锁中标识是否一致
if(redis.call('get', KEYS[1]) == ARGS[1]) then
    -- 释放锁
    return redis.call('del', KEYS[1])
end
return 0
